type Props = {
  /**
   * Base path without extension or size suffix, e.g. "/images/homepage".
   * Variants are expected at `{src}-400.webp`, `{src}-800.webp`, `{src}-1600.webp`,
   * with a JPEG fallback at `{src}-1200.jpg`. Generated by scripts/optimize-images.mjs.
   */
  src: string;
  alt: string;
  /** When true: fetched eagerly with high priority (use for above-the-fold hero only). */
  priority?: boolean;
  /** Native sizes attribute. Defaults to "100vw". */
  sizes?: string;
  className?: string;
  /** Inline style passthrough (e.g. object-position). */
  style?: React.CSSProperties;
  widths?: number[];
  /** Intrinsic width of the source image — lets the browser reserve layout space. */
  width?: number;
  /** Intrinsic height of the source image — lets the browser reserve layout space. */
  height?: number;
};

export default function ResponsiveImage({
  src,
  alt,
  priority = false,
  sizes = '100vw',
  className,
  style,
  widths = [400, 800, 1600],
  width,
  height,
}: Props) {
  const webpSrcSet = widths.map((w) => `${src}-${w}.webp ${w}w`).join(', ');
  const fallback = `${src}-1200.jpg`;

  return (
    <picture>
      <source type="image/webp" srcSet={webpSrcSet} sizes={sizes} />
      <img
        src={fallback}
        alt={alt}
        width={width}
        height={height}
        loading={priority ? 'eager' : 'lazy'}
        decoding="async"
        // @ts-ignore - fetchpriority lowercase is the correct HTML attribute
        fetchpriority={priority ? 'high' : 'auto'}
        className={className}
        style={style}
      />
    </picture>
  );
}
