// Downloads the Latin subsets of EB Garamond + Jost from Google Fonts and
// rewrites the @font-face declarations to point at self-hosted /fonts/*.woff2.
// Run once after changing the font selection: node scripts/download-fonts.mjs

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const fontsDir = path.join(repoRoot, 'public', 'fonts');
const outCssPath = path.join(repoRoot, 'src', 'assets', 'fonts.css');

const GOOGLE_CSS_URL =
  'https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=Jost:ital,wght@0,300;0,400;0,500;1,300&display=swap';

// Modern UA needed to get woff2 URLs; default UA gets ttf.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

await fs.mkdir(fontsDir, { recursive: true });

console.log('Fetching Google Fonts CSS...');
const cssResp = await fetch(GOOGLE_CSS_URL, { headers: { 'User-Agent': UA } });
const css = await cssResp.text();

// Split into "/* {subset} */ @font-face { ... }" blocks
const blockRe = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g;
const wanted = new Set(['latin', 'latin-ext']);
const blocks = [];
let m;
while ((m = blockRe.exec(css)) !== null) {
  const subset = m[1];
  const block = m[2];
  if (!wanted.has(subset)) continue;
  blocks.push({ subset, block });
}

console.log(`Keeping ${blocks.length} latin/latin-ext blocks`);

const rewritten = [];
for (const { subset, block } of blocks) {
  const urlMatch = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/);
  const familyMatch = block.match(/font-family:\s*'([^']+)'/);
  const weightMatch = block.match(/font-weight:\s*(\d+)/);
  const styleMatch = block.match(/font-style:\s*(\w+)/);
  if (!urlMatch || !familyMatch || !weightMatch || !styleMatch) continue;

  const url = urlMatch[1];
  const family = familyMatch[1].toLowerCase().replace(/\s+/g, '-');
  const weight = weightMatch[1];
  const style = styleMatch[1];
  const filename = `${family}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;
  const dst = path.join(fontsDir, filename);

  const resp = await fetch(url, { headers: { 'User-Agent': UA } });
  const buf = Buffer.from(await resp.arrayBuffer());
  await fs.writeFile(dst, buf);

  const newBlock = block.replace(/url\([^)]+\)/, `url(/fonts/${filename})`);
  rewritten.push(`/* ${subset} */\n${newBlock}`);
  process.stdout.write(`  ✓ ${filename} (${Math.round(buf.length / 1024)} KB)\n`);
}

const finalCss = `/* Auto-generated by scripts/download-fonts.mjs. Do not edit by hand. */\n${rewritten.join('\n\n')}\n`;
await fs.mkdir(path.dirname(outCssPath), { recursive: true });
await fs.writeFile(outCssPath, finalCss, 'utf-8');

console.log(`\n✓ Wrote ${outCssPath}`);
